services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mdd_inventory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: public
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.prod
    expose:
      - 3000
    networks:
      - inventory_network
volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge